// @flow

// USER
export const USER_SET = "USER_SET";
export const USER_SET_FOLLOWINGS = "USER_SET_FOLLOWINGS";
export const USER_SET_LIKES = "USER_SET_LIKES";
export const USER_SET_NEW_FEED_ITEMS = "USER_SET_NEW_FEED_ITEMS";
export const USER_SET_PLAYLISTS = "USER_SET_PLAYLISTS";
export const USER_SET_LIKE = "USER_SET_LIKE";
export const USER_ADD_LIKE = "USER_ADD_LIKE";
export const USER_SET_FOLLOWING = "USER_SET_FOLLOWING";
export const USER_ADD_FOLLOWING = "USER_ADD_FOLLOWING";

// PLAYLIST
export const PLAYLIST_SET = "PLAYLIST_SET";
export const PLAYLIST_IS_FETCHING = "PLAYLIST_IS_FETCHING";

// PLAYER
export const PLAYER_SET_TIME = "PLAYER_SET_TIME";
export const PLAYER_SET_TRACK = "PLAYER_SET_TRACK";
export const PLAYER_TOGGLE_PLAYING = "PLAYER_TOGGLE_PLAYING";
export const PLAYER_SET_PLAYLIST = "PLAYER_SET_PLAYLIST";

// TRACKS

export const TRACK_ADD = "TRACK_ADD";
export const TRACK_ADD_COMMENTS = "TRACK_ADD_COMMENTS";
