// @flow

// USER
export const USER_SET = "USER_SET";
export const USER_SET_FOLLOWINGS = "USER_SET_FOLLOWINGS";
export const USER_SET_LIKES = "USER_SET_LIKES";
export const USER_SET_NEW_FEED_ITEMS = "USER_SET_NEW_FEED_ITEMS";
export const USER_SET_PLAYLISTS = "USER_SET_PLAYLISTS";
export const USER_SET_LIKE = "USER_SET_LIKE";
export const USER_ADD_LIKE = "USER_ADD_LIKE";
export const USER_SET_FOLLOWING = "USER_SET_FOLLOWING";
export const USER_ADD_FOLLOWING = "USER_ADD_FOLLOWING";

// PLAYER
export const PLAYER_SET_TIME = "PLAYER_SET_TIME";
export const PLAYER_SET_TRACK = "PLAYER_SET_TRACK";
export const PLAYER_TOGGLE_PLAYING = "PLAYER_TOGGLE_PLAYING";
export const PLAYER_SET_PLAYLIST = "PLAYER_SET_PLAYLIST";

// TRACKS

export const TRACK_ADD = "TRACK_ADD";
export const TRACK_UPDATE_IMAGE = "TRACK_UPDATE_IMAGE";


// OBJECT

export const OBJECT_IS_FETCHING = "OBJECT_IS_FETCHING";
export const OBJECT_SET = "OBJECT_SET";
export const OBJECT_SET_NEW_ITEMS = "OBJECT_SET_NEW_ITEMS";

// APP

export const APP_TOGGLE_OFFLINE = "APP_TOGGLE_OFFLINE";
export const APP_PUSH_OFFLINE_QUEUE = "APP_PUSH_OFFLINE_QUEUE";
export const APP_POP_OFFLINE_QUEUE = "APP_POP_OFFLINE_QUEUE";
export const APP_CLEAR_OFFLINE_QUEUE = "APP_CLEAR_OFFLINE_QUEUE";
export const APP_SET_LOADED = "APP_SET_LOADED";
