// @flow

export const REQUEST_SONGS = 'REQUEST_SONGS';

export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_LIKES = 'RECEIVE_LIKES';
export const RECEIVE_PLAYLIST = 'RECEIVE_PLAYLIST';
export const RECEIVE_NEW_STREAM_SONGS = 'RECEIVE_NEW_STREAM_SONGS';
export const RECEIVE_FOLLOWINGS = 'RECEIVE_FOLLOWINGS';
export const RECEIVE_PLAYLISTS = 'RECEIVE_PLAYLISTS';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';